---
build_from:
  aarch64: ghcr.io/hassio-addons/base:16.3.0
  amd64: ghcr.io/hassio-addons/base:16.3.0
  armv7: ghcr.io/hassio-addons/base:16.3.0
codenotary:
  base_image: josiah@chilldivision.co.nz
  signer: josiah@chilldivision.co.nz
